name: Generate Video

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Generate MP4
        run: python life_game.py

      - name: Upload MP4
        uses: actions/upload-artifact@v4
        with:
          name: black_hole
          path: black_hole.mp4
